# Generated by Django 4.1.3 on 2022-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geacexdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
