# Generated by Django 4.1.3 on 2022-12-01 12:14

from django.db import migrations
from geacexdb.models import LISTA_CURSOS, DIAS_SEMANA, HORAS_DIA

def load_initial_data(apps, schema_editor):
    
    curso_modelo = apps.get_model('geacexdb', 'Curso')
    franja_modelo = apps.get_model('geacexdb', 'Franja')

    for curso in LISTA_CURSOS:

        curso_modelo.objects.create (
        nombre = curso[0]
    )

    for dia_s in DIAS_SEMANA:
        for hora_d in HORAS_DIA:

            franja_modelo.objects.create (
            dia=dia_s[0],
            hora=hora_d[0]
            )

class Migration(migrations.Migration):

    dependencies = [
        ('geacexdb', '0002_alter_centro_codigo'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
