# Generated by Django 4.1.3 on 2022-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geacexdb', '0003_auto_20221201_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
