# Generated by Django 4.1.3 on 2022-12-19 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geacexdb', '0004_alumno_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='franjas',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='grupo',
            name='calendario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geacexdb.calendario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='franja',
            name='dia',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], max_length=1),
        ),
    ]
