# Generated by Django 4.1.3 on 2022-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geacexdb', '0005_remove_calendario_franjas_remove_grupo_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='año',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='franja',
        ),
        migrations.AddField(
            model_name='calendario',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='franjas',
            field=models.ManyToManyField(to='geacexdb.franja'),
        ),
    ]
