# Generated by Django 4.1.3 on 2022-12-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geacexdb', '0006_remove_calendario_año_remove_grupo_franja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='plazo_preinscripcion',
            new_name='plazo_inscripcion',
        ),
    ]
